"""ajuste contratos

Revision ID: 0eea3b8451d4
Revises: 8353320007fd
Create Date: 2026-02-09 09:41:21.319220

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0eea3b8451d4"
down_revision: Union[str, None] = '8353320007fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('frete_brl_total', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('contracts', sa.Column('frete_brl_per_ton', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('contracts', sa.Column('frete_obs', sa.String(length=255), nullable=True))
    op.add_column('hedge_fx', sa.Column('volume_ton', sa.Numeric(precision=14, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hedge_fx', 'volume_ton')
    op.drop_column('contracts', 'frete_obs')
    op.drop_column('contracts', 'frete_brl_per_ton')
    op.drop_column('contracts', 'frete_brl_total')
    # ### end Alembic commands ###
