"""add ativo to farms

Revision ID: 180a0f4922d6
Revises: c3d688dbaff9
Create Date: 2026-02-05 09:28:31.465560

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "180a0f4922d6"
down_revision: Union[str, None] = 'c3d688dbaff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_constraint('farms_nome_key', 'farms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('farms_nome_key', 'farms', ['nome'])
    op.drop_column('farms', 'ativo')
    # ### end Alembic commands ###
