"""ajuste cbot quote

Revision ID: 493d16cbb648
Revises: 0eea3b8451d4
Create Date: 2026-02-11 16:26:14.471482

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "493d16cbb648"
down_revision: Union[str, None] = '0eea3b8451d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cbot_quotes', sa.Column('ref_mes', sa.Date(), nullable=True))
    op.drop_constraint('uq_cbot_quotes_farm_ts_symbol', 'cbot_quotes', type_='unique')
    op.create_index('ix_cbot_quotes_farm_symbol_refmes_ts', 'cbot_quotes', ['farm_id', 'symbol', 'ref_mes', 'capturado_em'], unique=False)
    op.create_index(op.f('ix_cbot_quotes_ref_mes'), 'cbot_quotes', ['ref_mes'], unique=False)
    op.create_unique_constraint('uq_cbot_quotes_farm_ts_symbol_refmes', 'cbot_quotes', ['farm_id', 'capturado_em', 'symbol', 'ref_mes'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cbot_quotes_farm_ts_symbol_refmes', 'cbot_quotes', type_='unique')
    op.drop_index(op.f('ix_cbot_quotes_ref_mes'), table_name='cbot_quotes')
    op.drop_index('ix_cbot_quotes_farm_symbol_refmes_ts', table_name='cbot_quotes')
    op.create_unique_constraint('uq_cbot_quotes_farm_ts_symbol', 'cbot_quotes', ['farm_id', 'capturado_em', 'symbol'])
    op.drop_column('cbot_quotes', 'ref_mes')
    # ### end Alembic commands ###
