"""models refactor step A

Revision ID: 71de7301ef6d
Revises: 180a0f4922d6
Create Date: 2026-02-05 11:33:34.990435

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71de7301ef6d"
down_revision: Union[str, None] = '180a0f4922d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_events_read'), 'alert_events', ['read'], unique=False)
    op.create_index(op.f('ix_alert_rules_ativo'), 'alert_rules', ['ativo'], unique=False)
    op.create_index(op.f('ix_alert_rules_nome'), 'alert_rules', ['nome'], unique=False)
    op.alter_column('cbot_quotes', 'price_usd_per_bu',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.create_index(op.f('ix_cbot_sources_ativo'), 'cbot_sources', ['ativo'], unique=False)
    op.create_index(op.f('ix_contracts_produto'), 'contracts', ['produto'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_tipo_precificacao'), 'contracts', ['tipo_precificacao'], unique=False)
    op.add_column('expenses_usd', sa.Column('competencia_mes', sa.Date(), nullable=True))
    op.drop_index('ix_expenses_usd_mes_competencia', table_name='expenses_usd')
    op.create_index(op.f('ix_expenses_usd_competencia_mes'), 'expenses_usd', ['competencia_mes'], unique=False)
    op.execute("""
    UPDATE expenses_usd
    SET competencia_mes = (to_date(mes_competencia || '-01', 'YYYY-MM-DD'))
    WHERE competencia_mes IS NULL
""")

    op.drop_column('expenses_usd', 'mes_competencia')
    op.create_index(op.f('ix_farms_nome'), 'farms', ['nome'], unique=False)
    op.add_column('fx_manual_points', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('fx_manual_points', 'fx',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.create_foreign_key(None, 'fx_manual_points', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('fx_model_points', 't_anos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('fx_model_points', 'dolar_sint',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_points', 'dolar_desc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'spot_usdbrl',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'cdi_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'sofr_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'offset_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'coupon_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'desconto_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'fx_manual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'fx_model',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'delta_abs',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'delta_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quotes', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fx_quotes', 'brl_per_usd',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.create_index(op.f('ix_fx_sources_ativo'), 'fx_sources', ['ativo'], unique=False)
    op.alter_column('fx_spot_ticks', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('hedge_cbot', 'cbot_usd_per_bu',
               existing_type=sa.NUMERIC(precision=14, scale=6),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.create_index(op.f('ix_hedge_cbot_ref_mes'), 'hedge_cbot', ['ref_mes'], unique=False)
    op.create_index(op.f('ix_hedge_cbot_symbol'), 'hedge_cbot', ['symbol'], unique=False)
    op.alter_column('hedge_fx', 'brl_per_usd',
               existing_type=sa.NUMERIC(precision=14, scale=6),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.create_index(op.f('ix_hedge_fx_ref_mes'), 'hedge_fx', ['ref_mes'], unique=False)
    op.alter_column('hedge_premium', 'premium_value',
               existing_type=sa.NUMERIC(precision=14, scale=6),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.add_column('interest_rates', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('interest_rates', 'cdi_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('interest_rates', 'sofr_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.drop_index('ix_interest_rates_farm_date', table_name='interest_rates')
    op.create_unique_constraint('uq_interest_rates_farm_date', 'interest_rates', ['farm_id', 'rate_date'])
    op.create_foreign_key(None, 'interest_rates', 'users', ['created_by_user_id'], ['id'])
    op.add_column('offset_calibration', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('offset_calibration', 'offset_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.drop_index('ix_offset_calibration_farm_id_id', table_name='offset_calibration')
    op.create_foreign_key(None, 'offset_calibration', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offset_calibration', type_='foreignkey')
    op.create_index('ix_offset_calibration_farm_id_id', 'offset_calibration', ['farm_id', 'id'], unique=False)
    op.alter_column('offset_calibration', 'offset_value',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('offset_calibration', 'created_by_user_id')
    op.drop_constraint(None, 'interest_rates', type_='foreignkey')
    op.drop_constraint('uq_interest_rates_farm_date', 'interest_rates', type_='unique')
    op.create_index('ix_interest_rates_farm_date', 'interest_rates', ['farm_id', 'rate_date'], unique=False)
    op.alter_column('interest_rates', 'sofr_annual',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('interest_rates', 'cdi_annual',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('interest_rates', 'created_by_user_id')
    op.alter_column('hedge_premium', 'premium_value',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=6),
               existing_nullable=False)
    op.drop_index(op.f('ix_hedge_fx_ref_mes'), table_name='hedge_fx')
    op.alter_column('hedge_fx', 'brl_per_usd',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=6),
               existing_nullable=False)
    op.drop_index(op.f('ix_hedge_cbot_symbol'), table_name='hedge_cbot')
    op.drop_index(op.f('ix_hedge_cbot_ref_mes'), table_name='hedge_cbot')
    op.alter_column('hedge_cbot', 'cbot_usd_per_bu',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=6),
               existing_nullable=False)
    op.alter_column('fx_spot_ticks', 'price',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_fx_sources_ativo'), table_name='fx_sources')
    op.alter_column('fx_quotes', 'brl_per_usd',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=False)
    op.alter_column('fx_quotes', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fx_quote_checks', 'delta_pct',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'delta_abs',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'fx_model',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_quote_checks', 'fx_manual',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'desconto_pct',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'coupon_annual',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'offset_value',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'sofr_annual',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'cdi_annual',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_runs', 'spot_usdbrl',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_points', 'dolar_desc',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_points', 'dolar_sint',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('fx_model_points', 't_anos',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'fx_manual_points', type_='foreignkey')
    op.alter_column('fx_manual_points', 'fx',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('fx_manual_points', 'created_by_user_id')
    op.drop_index(op.f('ix_farms_nome'), table_name='farms')
    op.add_column('expenses_usd', sa.Column('mes_competencia', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_expenses_usd_competencia_mes'), table_name='expenses_usd')
    op.create_index('ix_expenses_usd_mes_competencia', 'expenses_usd', ['mes_competencia'], unique=False)
    op.drop_column('expenses_usd', 'competencia_mes')
    op.drop_index(op.f('ix_contracts_tipo_precificacao'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_produto'), table_name='contracts')
    op.drop_index(op.f('ix_cbot_sources_ativo'), table_name='cbot_sources')
    op.alter_column('cbot_quotes', 'price_usd_per_bu',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_alert_rules_nome'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_ativo'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_events_read'), table_name='alert_events')
    # ### end Alembic commands ###
