"""init

Revision ID: 95cde9a035da
Revises: 
Create Date: 2026-02-04 17:34:40.628239

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95cde9a035da"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbot_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_cbot_sources_nome')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fx_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_fx_sources_nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('params_json', sa.String(length=1000), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_farm_id'), 'alert_rules', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_tipo'), 'alert_rules', ['tipo'], unique=False)
    op.create_table('cbot_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('price_usd_per_bu', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['cbot_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'capturado_em', 'symbol', name='uq_cbot_quotes_farm_ts_symbol')
    )
    op.create_index(op.f('ix_cbot_quotes_capturado_em'), 'cbot_quotes', ['capturado_em'], unique=False)
    op.create_index(op.f('ix_cbot_quotes_farm_id'), 'cbot_quotes', ['farm_id'], unique=False)
    op.create_index(op.f('ix_cbot_quotes_source_id'), 'cbot_quotes', ['source_id'], unique=False)
    op.create_index(op.f('ix_cbot_quotes_symbol'), 'cbot_quotes', ['symbol'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=20), nullable=False),
    sa.Column('tipo_precificacao', sa.String(length=20), nullable=False),
    sa.Column('volume_input_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume_input_unit', sa.String(length=10), nullable=False),
    sa.Column('volume_total_ton', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preco_fixo_brl_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('preco_fixo_brl_unit', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_data_entrega'), 'contracts', ['data_entrega'], unique=False)
    op.create_index(op.f('ix_contracts_farm_id'), 'contracts', ['farm_id'], unique=False)
    op.create_table('expenses_usd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('mes_competencia', sa.String(length=7), nullable=False),
    sa.Column('valor_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_usd_farm_id'), 'expenses_usd', ['farm_id'], unique=False)
    op.create_index(op.f('ix_expenses_usd_mes_competencia'), 'expenses_usd', ['mes_competencia'], unique=False)
    op.create_table('farm_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'user_id', name='uq_farm_users_farm_user')
    )
    op.create_index(op.f('ix_farm_users_farm_id'), 'farm_users', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_users_user_id'), 'farm_users', ['user_id'], unique=False)
    op.create_table('fx_manual_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref_mes', sa.Date(), nullable=False),
    sa.Column('fx', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['fx_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'source_id', 'captured_at', 'ref_mes', name='uq_fx_manual_point')
    )
    op.create_index(op.f('ix_fx_manual_points_captured_at'), 'fx_manual_points', ['captured_at'], unique=False)
    op.create_index(op.f('ix_fx_manual_points_farm_id'), 'fx_manual_points', ['farm_id'], unique=False)
    op.create_index(op.f('ix_fx_manual_points_ref_mes'), 'fx_manual_points', ['ref_mes'], unique=False)
    op.create_index(op.f('ix_fx_manual_points_source_id'), 'fx_manual_points', ['source_id'], unique=False)
    op.create_table('fx_model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('as_of_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_usdbrl', sa.Float(), nullable=False),
    sa.Column('cdi_annual', sa.Float(), nullable=False),
    sa.Column('sofr_annual', sa.Float(), nullable=False),
    sa.Column('offset_value', sa.Float(), nullable=False),
    sa.Column('coupon_annual', sa.Float(), nullable=False),
    sa.Column('desconto_pct', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_model_runs_as_of_ts'), 'fx_model_runs', ['as_of_ts'], unique=False)
    op.create_index(op.f('ix_fx_model_runs_farm_id'), 'fx_model_runs', ['farm_id'], unique=False)
    op.create_table('fx_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref_mes', sa.Date(), nullable=False),
    sa.Column('brl_per_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['fx_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'source_id', 'capturado_em', 'ref_mes', name='uq_fx_quote')
    )
    op.create_index(op.f('ix_fx_quotes_capturado_em'), 'fx_quotes', ['capturado_em'], unique=False)
    op.create_index(op.f('ix_fx_quotes_farm_id'), 'fx_quotes', ['farm_id'], unique=False)
    op.create_index(op.f('ix_fx_quotes_ref_mes'), 'fx_quotes', ['ref_mes'], unique=False)
    op.create_index(op.f('ix_fx_quotes_source_id'), 'fx_quotes', ['source_id'], unique=False)
    op.create_table('fx_spot_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'ts', name='uq_fx_spot_ticks_farm_ts')
    )
    op.create_index(op.f('ix_fx_spot_ticks_farm_id'), 'fx_spot_ticks', ['farm_id'], unique=False)
    op.create_index(op.f('ix_fx_spot_ticks_ts'), 'fx_spot_ticks', ['ts'], unique=False)
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('cdi_annual', sa.Float(), nullable=False),
    sa.Column('sofr_annual', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interest_rates_farm_date', 'interest_rates', ['farm_id', 'rate_date'], unique=False)
    op.create_index(op.f('ix_interest_rates_farm_id'), 'interest_rates', ['farm_id'], unique=False)
    op.create_index(op.f('ix_interest_rates_rate_date'), 'interest_rates', ['rate_date'], unique=False)
    op.create_table('offset_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('offset_value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offset_calibration_farm_id'), 'offset_calibration', ['farm_id'], unique=False)
    op.create_index('ix_offset_calibration_farm_id_id', 'offset_calibration', ['farm_id', 'id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_farm_id'), 'alert_events', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_triggered_at'), 'alert_events', ['triggered_at'], unique=False)
    op.create_table('fx_model_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ref_mes', sa.Date(), nullable=False),
    sa.Column('t_anos', sa.Float(), nullable=False),
    sa.Column('dolar_sint', sa.Float(), nullable=False),
    sa.Column('dolar_desc', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['fx_model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'ref_mes', name='uq_fx_model_points_run_ref')
    )
    op.create_index(op.f('ix_fx_model_points_ref_mes'), 'fx_model_points', ['ref_mes'], unique=False)
    op.create_index(op.f('ix_fx_model_points_run_id'), 'fx_model_points', ['run_id'], unique=False)
    op.create_table('hedge_cbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume_input_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume_input_unit', sa.String(length=10), nullable=False),
    sa.Column('volume_ton', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('cbot_usd_per_bu', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('ref_mes', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hedge_cbot_contract_id'), 'hedge_cbot', ['contract_id'], unique=False)
    op.create_index(op.f('ix_hedge_cbot_executado_em'), 'hedge_cbot', ['executado_em'], unique=False)
    op.create_table('hedge_fx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usd_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('brl_per_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('ref_mes', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hedge_fx_contract_id'), 'hedge_fx', ['contract_id'], unique=False)
    op.create_index(op.f('ix_hedge_fx_executado_em'), 'hedge_fx', ['executado_em'], unique=False)
    op.create_table('hedge_premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('executado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume_input_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume_input_unit', sa.String(length=10), nullable=False),
    sa.Column('volume_ton', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('premium_value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('premium_unit', sa.String(length=20), nullable=False),
    sa.Column('base_local', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hedge_premium_contract_id'), 'hedge_premium', ['contract_id'], unique=False)
    op.create_index(op.f('ix_hedge_premium_executado_em'), 'hedge_premium', ['executado_em'], unique=False)
    op.create_table('fx_quote_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('manual_point_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('model_point_id', sa.Integer(), nullable=True),
    sa.Column('ref_mes', sa.Date(), nullable=False),
    sa.Column('fx_manual', sa.Float(), nullable=False),
    sa.Column('fx_model', sa.Float(), nullable=False),
    sa.Column('delta_abs', sa.Float(), nullable=False),
    sa.Column('delta_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_point_id'], ['fx_manual_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_point_id'], ['fx_model_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_run_id'], ['fx_model_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_quote_checks_farm_id'), 'fx_quote_checks', ['farm_id'], unique=False)
    op.create_index(op.f('ix_fx_quote_checks_manual_point_id'), 'fx_quote_checks', ['manual_point_id'], unique=False)
    op.create_index(op.f('ix_fx_quote_checks_model_point_id'), 'fx_quote_checks', ['model_point_id'], unique=False)
    op.create_index(op.f('ix_fx_quote_checks_model_run_id'), 'fx_quote_checks', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_fx_quote_checks_ref_mes'), 'fx_quote_checks', ['ref_mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fx_quote_checks_ref_mes'), table_name='fx_quote_checks')
    op.drop_index(op.f('ix_fx_quote_checks_model_run_id'), table_name='fx_quote_checks')
    op.drop_index(op.f('ix_fx_quote_checks_model_point_id'), table_name='fx_quote_checks')
    op.drop_index(op.f('ix_fx_quote_checks_manual_point_id'), table_name='fx_quote_checks')
    op.drop_index(op.f('ix_fx_quote_checks_farm_id'), table_name='fx_quote_checks')
    op.drop_table('fx_quote_checks')
    op.drop_index(op.f('ix_hedge_premium_executado_em'), table_name='hedge_premium')
    op.drop_index(op.f('ix_hedge_premium_contract_id'), table_name='hedge_premium')
    op.drop_table('hedge_premium')
    op.drop_index(op.f('ix_hedge_fx_executado_em'), table_name='hedge_fx')
    op.drop_index(op.f('ix_hedge_fx_contract_id'), table_name='hedge_fx')
    op.drop_table('hedge_fx')
    op.drop_index(op.f('ix_hedge_cbot_executado_em'), table_name='hedge_cbot')
    op.drop_index(op.f('ix_hedge_cbot_contract_id'), table_name='hedge_cbot')
    op.drop_table('hedge_cbot')
    op.drop_index(op.f('ix_fx_model_points_run_id'), table_name='fx_model_points')
    op.drop_index(op.f('ix_fx_model_points_ref_mes'), table_name='fx_model_points')
    op.drop_table('fx_model_points')
    op.drop_index(op.f('ix_alert_events_triggered_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_farm_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_offset_calibration_farm_id_id', table_name='offset_calibration')
    op.drop_index(op.f('ix_offset_calibration_farm_id'), table_name='offset_calibration')
    op.drop_table('offset_calibration')
    op.drop_index(op.f('ix_interest_rates_rate_date'), table_name='interest_rates')
    op.drop_index(op.f('ix_interest_rates_farm_id'), table_name='interest_rates')
    op.drop_index('ix_interest_rates_farm_date', table_name='interest_rates')
    op.drop_table('interest_rates')
    op.drop_index(op.f('ix_fx_spot_ticks_ts'), table_name='fx_spot_ticks')
    op.drop_index(op.f('ix_fx_spot_ticks_farm_id'), table_name='fx_spot_ticks')
    op.drop_table('fx_spot_ticks')
    op.drop_index(op.f('ix_fx_quotes_source_id'), table_name='fx_quotes')
    op.drop_index(op.f('ix_fx_quotes_ref_mes'), table_name='fx_quotes')
    op.drop_index(op.f('ix_fx_quotes_farm_id'), table_name='fx_quotes')
    op.drop_index(op.f('ix_fx_quotes_capturado_em'), table_name='fx_quotes')
    op.drop_table('fx_quotes')
    op.drop_index(op.f('ix_fx_model_runs_farm_id'), table_name='fx_model_runs')
    op.drop_index(op.f('ix_fx_model_runs_as_of_ts'), table_name='fx_model_runs')
    op.drop_table('fx_model_runs')
    op.drop_index(op.f('ix_fx_manual_points_source_id'), table_name='fx_manual_points')
    op.drop_index(op.f('ix_fx_manual_points_ref_mes'), table_name='fx_manual_points')
    op.drop_index(op.f('ix_fx_manual_points_farm_id'), table_name='fx_manual_points')
    op.drop_index(op.f('ix_fx_manual_points_captured_at'), table_name='fx_manual_points')
    op.drop_table('fx_manual_points')
    op.drop_index(op.f('ix_farm_users_user_id'), table_name='farm_users')
    op.drop_index(op.f('ix_farm_users_farm_id'), table_name='farm_users')
    op.drop_table('farm_users')
    op.drop_index(op.f('ix_expenses_usd_mes_competencia'), table_name='expenses_usd')
    op.drop_index(op.f('ix_expenses_usd_farm_id'), table_name='expenses_usd')
    op.drop_table('expenses_usd')
    op.drop_index(op.f('ix_contracts_farm_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_data_entrega'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_cbot_quotes_symbol'), table_name='cbot_quotes')
    op.drop_index(op.f('ix_cbot_quotes_source_id'), table_name='cbot_quotes')
    op.drop_index(op.f('ix_cbot_quotes_farm_id'), table_name='cbot_quotes')
    op.drop_index(op.f('ix_cbot_quotes_capturado_em'), table_name='cbot_quotes')
    op.drop_table('cbot_quotes')
    op.drop_index(op.f('ix_alert_rules_tipo'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_farm_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fx_sources')
    op.drop_table('farms')
    op.drop_table('cbot_sources')
    # ### end Alembic commands ###
