"""fx_quote_check_link_quote

Revision ID: c3d688dbaff9
Revises: 95cde9a035da
Create Date: 2026-02-04 18:04:02.448498

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3d688dbaff9"
down_revision: Union[str, None] = '95cde9a035da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fx_quote_checks', sa.Column('quote_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_fx_quote_checks_quote_id'), 'fx_quote_checks', ['quote_id'], unique=False)
    op.create_unique_constraint('uq_fx_quote_checks_quote_id', 'fx_quote_checks', ['quote_id'])
    op.create_foreign_key(None, 'fx_quote_checks', 'fx_quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fx_quote_checks', type_='foreignkey')
    op.drop_constraint('uq_fx_quote_checks_quote_id', 'fx_quote_checks', type_='unique')
    op.drop_index(op.f('ix_fx_quote_checks_quote_id'), table_name='fx_quote_checks')
    op.drop_column('fx_quote_checks', 'quote_id')
    # ### end Alembic commands ###
